unit dutil.util.container.DynArrayTest;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, dutil.util.container.DynArray;

type
  // Test methods for class TDynArray
  TDynArrayTest = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAppend;
    procedure TestAppend1;
  end;

implementation

procedure TDynArrayTest.SetUp;
begin
end;

procedure TDynArrayTest.TearDown;
begin
end;

procedure TDynArrayTest.TestAppend;
var
  ReturnValue: Cardinal;
  Item: string;
  Destination: TArray<string>;
begin
  SetLength(Destination, 2);
  Destination[0] := 'item 1';
  Destination[1] := 'item 2';
  Item := 'item 3';
  ReturnValue := TDynArray.Append<string>(Destination, Item);
  CheckEquals(3, ReturnValue);
  CheckEquals(Destination[2], Item);
end;

procedure TDynArrayTest.TestAppend1;
var
  ReturnValue: Cardinal;
  Items: TArray<string>;
  Destination: TArray<string>;
begin
  SetLength(Destination, 2);
  Destination[0] := 'item 1';
  Destination[1] := 'item 2';
  SetLength(Items, 2);
  Items[0] := 'item 3';
  Items[1] := 'item 4';
  ReturnValue := TDynArray.Append<string>(Destination, Items);
  CheckEquals(4, ReturnValue);
  CheckEquals(Destination[2], Items[0]);
  CheckEquals(Destination[3], Items[1]);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TDynArrayTest.Suite);
end.

